/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ProgrammRouteImport } from './routes/programm'
import { Route as MitgliedWerdenRouteImport } from './routes/mitglied-werden'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FrauenrechteRouteImport } from './routes/frauenrechte'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammRoute = ProgrammRouteImport.update({
  id: '/programm',
  path: '/programm',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliedWerdenRoute = MitgliedWerdenRouteImport.update({
  id: '/mitglied-werden',
  path: '/mitglied-werden',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FrauenrechteRoute = FrauenrechteRouteImport.update({
  id: '/frauenrechte',
  path: '/frauenrechte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/frauenrechte': typeof FrauenrechteRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/programm': typeof ProgrammRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/frauenrechte': typeof FrauenrechteRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/programm': typeof ProgrammRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/frauenrechte': typeof FrauenrechteRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/programm': typeof ProgrammRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/frauenrechte'
    | '/kontakt'
    | '/mitglied-werden'
    | '/programm'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/frauenrechte'
    | '/kontakt'
    | '/mitglied-werden'
    | '/programm'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/frauenrechte'
    | '/kontakt'
    | '/mitglied-werden'
    | '/programm'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrauenrechteRoute: typeof FrauenrechteRoute
  KontaktRoute: typeof KontaktRoute
  MitgliedWerdenRoute: typeof MitgliedWerdenRoute
  ProgrammRoute: typeof ProgrammRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm': {
      id: '/programm'
      path: '/programm'
      fullPath: '/programm'
      preLoaderRoute: typeof ProgrammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglied-werden': {
      id: '/mitglied-werden'
      path: '/mitglied-werden'
      fullPath: '/mitglied-werden'
      preLoaderRoute: typeof MitgliedWerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frauenrechte': {
      id: '/frauenrechte'
      path: '/frauenrechte'
      fullPath: '/frauenrechte'
      preLoaderRoute: typeof FrauenrechteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrauenrechteRoute: FrauenrechteRoute,
  KontaktRoute: KontaktRoute,
  MitgliedWerdenRoute: MitgliedWerdenRoute,
  ProgrammRoute: ProgrammRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
